### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by arvind-das** [TouK/excel-export#47]
Hi

Thanks for creating this awesome plugin . While working with grails 3.0.7, installing this plugin gives error, the complete stacktrace is here : 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is java.lang.UnsupportedClassVersionError: pl/touk/excel/export/ExcelExportGrailsPlugin : Unsupported major.minor version 52.0
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 22 more
Caused by: java.lang.UnsupportedClassVersionError: pl/touk/excel/export/ExcelExportGrailsPlugin : Unsupported major.minor version 52.0


```

I am using JDK7
Please help me out.
Cheers!

**Comment by eratolekov** [comment]
Hi arvind-das

52 major number means java8.
https://en.wikipedia.org/wiki/Java_class_file

You have to use java8.

**Comment by arvind-das** [comment]
Thanks for the update. Actually I forgot to comment back. I already
upgraded to java 8 and it worked . but I would like to suggest to compile
it for jdk 7 if possible. Mostly people are on jdk 7.

**Comment by beni4ka** [comment]
I would like to support the proposal for a Java 7 compilation. We have our reasons we can not upgrade our project to Java 8, but we need to use excel export grails plugin. Can you advice me if there is any way to use it with jdk 7?
